# Generated by Django 2.2.3 on 2019-07-10 00:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0003_auto_20190510_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoi',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='geometry_final',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3857, verbose_name='Final Polygon Geometry'),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='geometry_orig',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3857, verbose_name='Original Polygon Geometry'),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='manipulators',
            field=models.TextField(blank=True, help_text='csv list of manipulators to be applied', null=True, verbose_name='Manipulator List'),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='aoi',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, null=True, related_name='drawing_aoi_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
        migrations.AlterField(
            model_name='windenergysite',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='windenergysite',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Modified'),
        ),
        migrations.AlterField(
            model_name='windenergysite',
            name='geometry_final',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3857, verbose_name='Final Polygon Geometry'),
        ),
        migrations.AlterField(
            model_name='windenergysite',
            name='geometry_orig',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=3857, verbose_name='Original Polygon Geometry'),
        ),
        migrations.AlterField(
            model_name='windenergysite',
            name='manipulators',
            field=models.TextField(blank=True, help_text='csv list of manipulators to be applied', null=True, verbose_name='Manipulator List'),
        ),
        migrations.AlterField(
            model_name='windenergysite',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='windenergysite',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, null=True, related_name='drawing_windenergysite_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
    ]
