# Generated by Django 2.2.3 on 2019-07-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0004_auto_20190710_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aoi',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='drawing_aoi_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
        migrations.AlterField(
            model_name='windenergysite',
            name='sharing_groups',
            field=models.ManyToManyField(blank=True, editable=False, related_name='drawing_windenergysite_related', to='auth.Group', verbose_name='Share with the following groups'),
        ),
    ]
